<?php
$guest = $this->forename . ' ' . $this->surname;
$name = $this->guestId;
?>
<tr>
  <td class="guest"><?php echo $guest; ?></td>
  <td class="center">
    <?php echo $this->formRadio($name, $this->receptionId, null, array(1 => '')); ?>
  </td>
  <td class="center">
    <?php echo $this->formRadio($name, $this->receptionId, null, array(2 => '')); ?>
  </td>
  <td class="center">
    <?php echo $this->formRadio($name, $this->receptionId, null, array(3 => '')); ?>
  </td>
  <td class="center">
    <?php echo $this->formRadio($name, $this->receptionId, null, array(4 => '')); ?>
  </td>
</tr>
