  <h1>Welcome <?php echo $this->greeting(); ?></h1>
  <p>We are very happy to be getting married, and hope that you will be able join us!</p>
  <p>We've tried to include all the information we think you'll need on this website. Please RSVP below.</p>
  <p>Unfortunately due to restricted space at our venue, we've had to take the difficult
  decision of only inviting adults to our wedding. We hope you can understand our predicament.</p>
  <img src="/images/joanna-greg.png" width="127" height="41" alt="Joanna & Greg" />
  <table>
    <tr>
  	  <td><h2>RSVP</h2></td>
  	  <td><div id="saved-rsvp" class="saved">Saved!</div></td>
  	</tr>
  </table>
  <form>
  <table class="rsvp listing">
    <tr class="first">
      <th>Guest</th><th class="center">Attending</th><th class="center">Not Attending</th>
    </tr>
    <?php echo $this->guests(); ?>
  </table>
  </form><br/>
  <table>
    <tr>
  	  <td><h2>Reception Drinks</h2></td>
  	  <td><div id="saved-recep" class="saved">Saved!</div></td>
  	</tr>
  </table>
  <p>We have provisioned for two reception drinks (possibly more depending on demand). A selection of 6 canapes will be served.</p>
  <form>
    <table class="reception listing">
      <tr class="first">
        <th>Guest</th>
        <th class="center">Champagne</th>
        <th class="center">Pimms &amp;<br/>Lemonade</th>
        <th class="center">Both</th>
        <th class="center">Orange Juice</th>
      </tr>
      <?php echo $this->receptionDrinks(); ?>
    </table>
  </form><br/>
  <table>
    <tr>
  	  <td><h2>Menu Preference</h2></td>
  	  <td><div id="saved-menu" class="saved">Saved!</div></td>
  	</tr>
  </table>
  <p>The menu is seasonal and therefore likely to change, these are examples dishes:
  <dl>
    <dt><b>Meat</b> - Slow cooked blade of beef topped with homemade pate sat on a croute with a creamy brandy sauce</dt>
    <dt><b>Fish</b> - Fillet of salmon with a lemon &amp; herb crust, champagne butter sauce and seasonal vegetables</dt>
    <dt><b>Vegetarian</b> - Saute vegetable wellington with a basil sauce</dt>
    <dt><b>Special</b> - If you have special dietary requirements / food allergies</dt>
  </dl>
  </p>
  <form>
    <?php echo $this->menuOptions(); ?>

  </form><br/>
  <table>
    <tr>
  	  <td><h2>Wine Preference</h2></td>
  	  <td><div id="saved-wine" class="saved">Saved!</div></td>
  	</tr>
  </table>
  <p>White wine on the table will be a New Zealand Sauvignon Blanc, the red will be a Spanish Tempranillo Rioja.<br/>
    <em>Red wine is only permitted in the Ballroom where the wedding breakfast is served</em>.</p>
  <form>
  <table class="wine listing">
    <tr class="first">
      <th>Guest</th><th class="center">White</th><th class="center">Red</th><th class="center">Neither</th>
    </tr>
    <?php echo $this->wineOptions(); ?>
  </table>
  </form><br/>
  <p>We will be sitting down for the wedding breakfast at approximately 4.15pm and an evening buffet served around 9pm.</p>
<script type="text/javascript" src="/js/rsvp.js"></script>
