  <h1>Welcome <?php echo $this->greeting(); ?></h1>
  <p>We are very happy to be getting married, and hope that you will be able join us!</p>
  <p>We've tried to include all the information we think you'll need on this website. Please RSVP below.</p>
  <p>Unfortunately due to restricted space at our venue, we've had to take the difficult
  decision of only inviting adults to our wedding. We hope you can understand our predicament.</p>
  <img src="/images/joanna-greg.png" width="127" height="41" alt="Joanna & Greg" />
  <h2>RSVP</h2>
  <form>
  <table class="rsvp listing">
    <tr class="first">
      <th>Guest</th><th class="center">Attending</th><th class="center">Not Attending</th>
    </tr>
    <?php echo $this->guests(); ?>
  </table>
  </form><br/>
  <h2>Reception Drinks</h2>
  <p>We have provisioned for two reception drinks (possibly more depending on demand). A selection of 6 canapes will be served.</p>
  <form>
    <table class="reception listing">
      <tr class="first">
        <th>Guest</th>
        <th class="center">Champagne</th>
        <th class="center">Pimms &amp;<br/>Lemonade</th>
        <th class="center">Both</th>
        <th class="center">Orange Juice</th>
      </tr>
      <?php echo $this->receptionDrinks(); ?>
    </table>
  </form><br/>
  <h2>Menu Preference</h2>
  <p>The menu is seasonal and therefore likely to change, these are examples dishes:
  <dl>
    <dt><b>Meat</b> - Slow cooked blade of beef topped with homemade pate sat on a croute with a creamy brandy sauce</dt>
    <dt><b>Fish</b> - Fillet of salmon with a lemon &amp; herb crust, champagne butter sauce and seasonal vegetables</dt>
    <dt><b>Vegetarian</b> - Saute vegetable wellington with a basil sauce</dt>
    <!-- <dt><b>Special</b> - If you have special dietary requirements / food allergies</dt> -->
  </dl>
  </p>
  <form>
    <table class="menu listing">
      <tr class="first">
        <th>Guest</th>
        <th class="center">Meat</th>
        <th class="center">Fish</th>
        <th class="center">Vegetarian</th>
        <!-- <th class="center">Special</th> -->
      </tr>
      <?php echo $this->menuOptions(); ?>
    </table>
    <!-- <div id="diet">
      <input type="text" name="dietary" id="require" maxlength="255" size="40" />
    </div> -->
  </form><br/>
  <h2>Wine Preference</h2>
  <p>White wine on the table will be a New Zealand Sauvignon Blanc, the red will be a Spanish Tempranillo Rioja.<br/>
    <em>Red wine is only permitted in the Ballroom where the wedding breakfast is served</em>.</p>
  <form>
  <table class="wine listing">
    <tr class="first">
      <th>Guest</th><th class="center">White</th><th class="center">Red</th><th class="center">Neither</th>
    </tr>
    <?php echo $this->wineOptions(); ?>
  </table>
  </form><br/>
  <p>We will be sitting down for the wedding breakfast at approximately 4.15pm and an evening buffet served around 9pm.</p>
<script type="text/javascript">
  $(function() {
    $('.rsvp input[type=radio]').change(submitRsvp);
    $('.reception input[type=radio]').change(submitReception);
    $('.menu input[type=radio]').change(
      function() {
        submitMenu($(this));
        // showDietary();
      }
    );
    $('.wine input[type=radio]').change(submitWine);
    /*
    $('#special-4').click(showDietary);
    $('#require').focus(showDietHint);
    $('#require').blur(hideDietHint);
    showDietary();
    */
  });

  function sorry(e) {
    alert("Sorry, there was a problem and we cannot record your RSVP, please try again later");
  }

  function submitRsvp() {
  	$.ajax({
  	  url: '/rsvp/attending',
  	  type: 'POST',
  	  data: 'guest=' + $(this).attr('name') + '&rsvp=' + $(this).attr('value'),
  	  success: function(msg) {
        // implement a cut off time
  	  },
  	  error: sorry
  	});
  }

  function submitReception() {
  	$.ajax({
  	  url: '/rsvp/reception',
  	  type: 'POST',
  	  data: 'guest=' + $(this).attr('name') + '&reception=' + $(this).attr('value'),
  	  success: function(msg) {
        // implement a cut off time
  	  },
  	  error: sorry
  	});
  }

  function submitMenu(radio) {
  	$.ajax({
  	  url: '/rsvp/menu',
  	  type: 'POST',
  	  data: 'guest=' + radio.attr('name') + '&menu=' + radio.attr('value'),
  	  success: function(msg) {
        // implement a cut off time
  	  },
  	  error: sorry
  	});
  }

  function submitWine() {
  	$.ajax({
  	  url: '/rsvp/wine',
  	  type: 'POST',
  	  data: 'guest=' + $(this).attr('name') + '&wine=' + $(this).attr('value'),
  	  success: function(msg) {
        // implement a cut off time
  	  },
  	  error: sorry
  	});
  }

  function showDietary() {
    var diet = $('#diet');
    if ($(this).attr('id') == 'special-4' || $('#special-4').attr('checked') == true) {
      if ($('#require').attr('value') == '')
        $('#require').attr('value', 'dietary requirements').css('color', '#bbbbbb');
      diet.slideDown();
    } else {
      diet.slideUp();
    }
  }

  function showDietHint() {
  	var txt = $(this);
  	if (txt.attr('value') == 'dietary requirements') {
  	  txt.attr('value', '');
  	  txt.css('color', '#000000');
  	}
  }

  function hideDietHint() {
  	var txt = $(this);
  	if (txt.attr('value') == '') {
      txt.css('color', '#bbbbbb');
  	  txt.attr('value', 'dietary requirements');
  	}
  }
</script>
