<?php echo $this->doctype('HTML5'); ?>

<html lang="en">
<head>
  <meta charset="utf-8">
  <!--[if ie]><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><![endif]-->
  <title>Joanna &amp; Greg's Big Day</title>
  <meta name="description" content="Joanna and Greg's wedding day">
  <meta name="author" content="Greg Knapp http://gregk.me">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="/css/jag.css">
  <script type="text/javascript"
    src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
  <script type="text/javascript" src="/js/jquery.effects.core.min.js"></script>
</head>
<body>
<div id="container">
  <?php echo $this->navigation(); ?>
  <div id="main" role="main">
  <?php echo $this->layout()->content; ?>
  </div>
  <div id="footer">
    <div class="float-left couple"><img src="/images/tiny-couple.png" width="43" height="28" alt="Image of a small wedding couple" /></div>
    <div class="float-left valign-middle">
      Saturday, 24th September 2011 @ <a href="http://www.themansionhouse.org" title="visit our wedding venue website">The Mansion House</a> /
      <a href="/logout">Logout</a>
    </div>
    <div class="clear"></div>
  </div>
</div>
<div id="hearts"><div id="go-home"><a href="/rsvp" title="Back to the homepage"> </a></div></div>
<script type="text/javascript">
  function animateHeader() {
    $('#hearts').animate(
      { top: '0' }, { duration: 700 }
    );
  }
  $(function() { animateHeader() });
</script>
</body>
</html>
