<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <!--[if ie]><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><![endif]-->
  <title>Joanna &amp; Greg&#145;s Big Day</title>
  <meta name="description" content="Joanna and Greg's wedding day">
  <meta name="author" content="Greg Knapp http://gregk.me">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="/css/jag.css">
</head>
<body>
<?php echo $this->layout()->content; ?>
</body>
</html>
