<?php echo $this->doctype('HTML5'); ?>

<html lang="en">
<head>
  <meta charset="utf-8">
  <!--[if ie]><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"><![endif]-->
  <title>Joanna &amp; Greg's Big Day</title>
  <meta name="description" content="Joanna and Greg's wedding day">
  <meta name="author" content="Greg Knapp http://gregk.me">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="/css/jag.css">
  <script type="text/javascript"
    src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
  <script type="text/javascript"
    src="/js/jquery.effects.core.min.js"></script>
  <script type="text/javascript">
    function animateHeader() {
      $('#hearts').animate(
        { top: '0' }, { duration: 700 }
      );
    }

    $(function() { animateHeader() });
  </script>
</head>
<body>
<section id="container">
<?php echo $this->navigation(); ?>
<div id="main" role="main">
<?php echo $this->layout()->content; ?>
</div>
  <footer>
      Saturday, 24th September 2011 @ <a href="http://www.themansionhouse.org">The Mansion House</a> /
      <a href="/logout">Logout</a>
  </footer>
</section>
<div id="hearts"> </div>
</body>
</html>
