<div id="login">
  <header>
    <a href="/"><image src="images/title.png" id="title" alt="Joanna and Greg's Big Day" /></a><br>
    <image src="images/couple.png" id="couple" alt="Cartoon wedding couple" /><br>
    <image src="images/date.png" id="date" />
  </header>
  <div id="main" role="main">
    <form method="post" action="/login">
      <input type="password" name="passcode" size="10" />
      <input type="submit" value="login" class="button" />
    </form>
    <p id="instructions">Please enter your passcode to login.</p>
    <p id="slug">
      This is your postcode and character at the bottom of your invitation.<br>
	  <a>Help me!</a>
	</p>
    <div id="help">
      <image src="images/invite-help.png"
        alt="Example invitation with character at bottom circled in red" />
        <p>If your postcode is SG6 7RT and the character<br>
        in your invitation is F, your passcode will be<br>SG67RTF.</p>
    </div>
  </div>
</div>
<script type="text/javascript" src="js/yepnope.1.0.1-min.js"></script>
<script type="text/javascript">
function jQueryLoaded() {
  $("#main a").click(function() {
    var help = $("#help");
    if (help.is(":hidden")) {
      $("#slug").slideUp(function() { help.slideDown(); });
    }
  });
}

yepnope({
  load: 'http://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js',
  callback: jQueryLoaded
});
</script>
