<div id="login">
  <header>
    <a href="/"><image src="/images/title.png" id="title" alt="Joanna and Greg's Big Day" /></a><br>
    <image src="/images/couple.png" id="couple" alt="Cartoon wedding couple" /><br>
    <image src="/images/date.png" id="date" />
  </header>
  <section role="main">
    <form method="post" action="/login">
      <input type="password" name="passcode" size="10" />
      <input type="submit" value="login" class="button" />
    </form>
    <p id="instructions"><?php echo $this->loginMessage(); ?></p>
    <p id="slug">
      Your passcode is your postcode &amp; character<br/> at the bottom of your invitation.<br>
	  <a>Help me!</a>
	</p>
    <div id="help">
      <image src="/images/invite-help.png"
        alt="Example invitation with character at bottom circled in red" />
        <p>If your postcode is SG6 7RT and the character in<br/>
        your invitation is F, your passcode will be: SG67RTF</p><br/>
    </div>
  </section>
</div>
