<?php
$guests = $this->guests->listRsvp();
$summary = $this->guests->summarise($guests);
?>
<div id="main" role="main">
  <h1>RSVP Summary</h1>
  <?php foreach ($summary as $question => $choices) { ?>
  	<p><b><?php echo ucfirst($question) ?></b>:
  	<?php
  	$output = array();
  	foreach ($choices as $choice => $totals) {
  	   $output[] = $choice . ': ' . $totals;
  	}
  	echo implode(' | ', $output);
  	?></p>
  <?php } ?>

  <table width="100%" class="listing">
    <tr class="first">
      <th>Guest</th><th>RSVP</th><th>Reception</th><th>Meal</th><th>Wine</th><th>Dietary</th>
    </tr>
<?php foreach ($guests as $guest) { ?>
<?php
    $rsvp = strtolower($guest['rsvp']);
    $fontColor = 'black';
    if ($rsvp == 'attending') {
    	$color = '#eeffee';
    	if (empty($guest['reception']) || empty($guest['menu']))
    		$color = '#ffcc99';

    	if ($guest['menu'] == 'Special')
    		$color = '#ccccff';
    } else if ($rsvp == 'not responded') {
    	$color = '#ffeeee';
    } else {
    	$color = '#f5f5f5';
    	$fontColor = '#bbb';
    }
    ?>
<tr style="background-color: <?php echo $color ?>; color: <?php echo $fontColor ?>;">
      <td><?php echo $guest['name'] ?></td>
      <td><?php echo $guest['rsvp'] ?></td>
      <td><?php echo $guest['reception'] ?></td>
      <td><?php echo $guest['menu'] ?></td>
      <td><?php echo $guest['wine'] ?></td>
      <td><?php echo $guest['dietary'] ?></td>
    </tr>
    <?php } ?>
  </table>
</div>
