<h1>Directions</h1>
<h2>From the South</h2>
<p>Our wedding venue is situated 3.5 miles west of Biggleswade in Bedfordshire. Heading north on the A1M,
after junction 10 please take the first left at the next roundabout, <a href="http://maps.google.co.uk/?ie=UTF8&ll=52.090529,-0.274315&spn=0.031167,0.07905&z=14&layer=c&cbll=52.090275,-0.274301&panoid=Pl2lDT-eXS0bNBhg6dwwIA&cbp=12,351,,0,6.82">sign posted Shefford (B658)</a>.</p>
<h2>From the North</h2>
<p>From the North pass Sandy on the A1M, you will approach a roundabout with a
Sainsbury's on your left, take the third exit <a href="http://maps.google.co.uk/?ie=UTF8&ll=52.095117,-0.274615&spn=0.015582,0.039525&z=15&layer=c&cbll=52.09555,-0.274682&panoid=8osY6qWQRgleii9rWUYrgg&cbp=12,167.81,,0,3.62">sign posted Shefford (B658)</a>.</p>
<div class="center">
  <h2 class="center">Your Journey</h2>
  <p><div id="canvas"></div></p>
  <p>Many sat navs (and Google Maps) will
  guide you to the wrong entrance. Below is the correct<br/>
  approach for The Mansion House at Old Warden Park (formerly Shuttleworth Park).</p>
  <img class="img" src="/images/approach.png" height="408" width="615" />
  <p>Please drive past the entrance to the Shuttleworth Collection / visitor
  centre and continue towards Old Warden.</p>
  <img class="img" src="/images/streetview.jpg" height="400" width="615" />
  <p>The <a href="http://maps.google.co.uk/maps?f=d&source=s_d&saddr=Old+Warden,+Biggleswade,+Central+Bedfordshire+SG18+9DX,+UK&daddr=52.0862588,-0.3400607+to:Hill+Ln%2FB658&hl=en&geocode=FSDDGgMdDAT7_ykft30wyMt3SDESOsaBh3s7ag%3BFfLFGgMdpM_6_ynX5yOjNcp3SDFBMfW3qBwOEw%3BFTLdGgMdusz7_w&gl=uk&mra=dpe&mrsp=1&sz=15&via=1&sll=52.086547,-0.328045&sspn=0.015347,0.034246&ie=UTF8&ll=52.083515,-0.347314&spn=0.014847,0.054331&z=15&layer=c&cbll=52.083596,-0.339301&panoid=p578pccEpLsbw3-BfzU59Q&cbp=12,119.61,,0,1.07">street view</a> of this approach.<br/>
  Take a left on this bend to enter Old Warden Park (aka Shuttleworth Park).</p><br/>
</div>
<div id="mansion-address">
  <p><strong>Venue address</strong><br/>
  <address>
  The Mansion House<br/>
  Old Warden Park<br/>
  Biggleswade<br/>
  Bedfordshire<br/>
  SG18 9DX
  </address>
  </p>
</div>
<div id="mansion">
  <img src="/images/mansion.jpg" class="img" />
</div>
<div class="clear"></div>
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">
  var directionDisplay;
  var directionsService;
  var map;

  function gmapLoader() {
    directionsService = new google.maps.DirectionsService();
    directionsDisplay = new google.maps.DirectionsRenderer();
    map = new google.maps.Map(
      document.getElementById("canvas"),
      { mapTypeId: google.maps.MapTypeId.ROADMAP }
    );
    directionsDisplay.setMap(map);
    calcRoute();
  }

  function calcRoute() {
    var request = {
      origin: '<?php echo $this->postcode(); ?>',
      destination: 'SG189DX',
      travelMode: google.maps.TravelMode.DRIVING
    };

    directionsService.route(request, function(result, status) {
      if (status == google.maps.DirectionsStatus.OK) {
        directionsDisplay.setDirections(result);
      } else {
      	alert("Apologies, your directions could not be loaded");
      }
    });
  }

  $(function () {
    gmapLoader();
  });
</script>
