<h1>Gifts</h1>
<p>Gifts are discretionary, it's more important to us that you can join us to celebrate our wedding.
If you would like to buy us a gift, we would be very grateful if you could help enhance our honeymoon.
In no particular order, the list of available upgrades are:</p>
<table class="listing gifts">
  <tr class="first">
    <th width="70%">Gift</th><th width="10%">Price</th><th width="10%">Requested</th><th width="10%">&nbsp;</th>
  </tr>
  <?php echo $this->gifts(); ?>
</table>