<?php if ($this->user->boughtGifts()): ?>
<h1>Thank you</h1>
<div class="notice">
  <p>We can't thank you enough for your gift(s)!</p>
  <p>You chose to buy us:
  <ul>
    <?php echo $this->boughtGifts(); ?>
  </ul>
  </p>
  <p>Our account details:
  <dl>
    <dt>Alliance &amp; Leicester</dt>
    <dt>Mr G D Knapp &amp; Miss J D Holmes</dt>
    <dt>a/c no. 72856681</dt>
    <dt>sort no. 09-01-32</dt>
  </dl>
  </p>
</div>
<?php else: ?>
<h1>Gifts</h1>
<p>The most important thing for us is that you can be with us to celebrate our special day. However, should you wish to
give us something for our married life together, a contribution to our honeymoon fund would be greatly appreciated,
helping make our honeymoon memories extra special and those that last a lifetime!</p>
<?php endif; ?>
<p>The list of available upgrades are:</p>
<form method="post" action="/gifts/buy">
<table class="listing gifts">
  <tr class="first">
    <th width="70%">Gift</th><th width="10%">Price</th><th width="10%">Requested</th><th width="10%">&nbsp;</th>
  </tr>
  <?php echo $this->gifts(); ?>
</table>
<div id="gifts-total">
	<div class="float-left left"><b>Total:</b>&nbsp; £<span>0</span></div>
	<div class="float-left right"><input type="submit" value="Buy upgrades" /></div>
</div>
<div class="clear"></div>
</form>
<h3>Where are we off to?</h3>
<div class="center">
	<img class="img" src="/images/meeru.jpg" />
	<p>We're heading to Meeru Island in the Maldives for two weeks.</p>
</div>
<script type="text/javascript">
	var selects;
	var lblTotal;
	var submit;

	function updateTotal() {
		var total = 0;

		selects.each(function(i) {
			var select = $(this);
			var price = getPrice(select);
			total += select.attr('value') * price;
		});

		submit.attr('disabled', (total > 0 ? false : true));
		lblTotal.html(total);
	}

	function getPrice(elem) {
		var prices = elem.parent().siblings().eq(-2).html().match(/(\d+)/);
		return prices[0];
	}

	$(function() {
		selects = $('form select');
		lblTotal = $('#gifts-total span');
		submit = $('form input[type=submit]');

		updateTotal();
		selects.each(function(i) {
			$(this).change(updateTotal);
		});
	});
</script>
