<h1>Accommodation</h1>
<p>Below is a list of local accommodation. We are staying at the Swan Hotel.</p>
<p>We can recommend The Barns Hotel having stayed there for a friends wedding.
We cannot offer personal recommendation for other venues. Room rates correct as of May 2011.</p>
<p>The bar will close at 11.30pm with the function finishing at midnight, please
<a href="http://maps.google.co.uk/maps?near=Old+Warden,+Biggleswade,+Central+Bedfordshire+SG18+9DX,+UK&geocode=CXDQUdDAgZxWFSDDGgMdDAT7_ykft30wyMt3SDESOsaBh3s7ag&q=taxis&f=l&sll=52.085783,-0.32665&sspn=0.007806,0.017874&ie=UTF8&hq=taxis&hnear=&ll=52.10039,-0.285645&spn=0.119578,0.285988&z=12">book taxis</a>
 to arrive between these times.</p><br/>
<table class="listing">
  <tr class="first">
  <th>Name &amp; Address</th>
  <th>Type</th>
  <th>Rate</th>
  <th>Distance</th>
  </tr>
  <tr>
    <td>
      <p><a href="http://www.themansionhouse.org/accommodation.aspx">The Mansion House</a> (wedding venue)<br/>
      Clock House, Old Warden, <a href="http://maps.google.co.uk/maps?q=the+mansion+house,+old+warden&sll=52.084609,-0.32856&sspn=0.015533,0.029311&ie=UTF8&z=15">SG18 9DX</a><br/>
       01767 626200 / <a href="mailto:enquiries@themansionhouse.org">E-mail</a></p>
    </td>
    <td>Bed &amp; Breakfast</td>
    <td>£52 - £85</td>
    <td>-</td>
  </tr>
  <tr>
    <td>
      <p><a href="http://www.oldwardenguesthouse.co.uk">The Old Warden Guest House</a><br/>
      Clock House, Old Warden, <a href="http://maps.google.co.uk/maps?f=d&source=s_d&saddr=Old+Warden,+Biggleswade,+Central+Bedfordshire+SG18+9DX,+UK&daddr=SG18+9HQ&hl=en&geocode=FSDDGgMdDAT7_ykft30wyMt3SDESOsaBh3s7ag%3B&mra=ls&sll=52.106755,-0.392895&sspn=0.1242,0.234489&ie=UTF8&z=15">SG18 9HQ</a><br/>
       01767 627201 / <a href="mailto:info@oldwardenguesthouse.co.uk">E-mail</a></p>
    </td>
    <td>Bed &amp; Breakfast</td>
    <td>£38 - £65</td>
    <td>1 mile</td>
  </tr>
  <tr>
    <td>
      <p><a href="http://www.letseat.at/greenmanstanford">The Green Man</a><br/>
      Stanford Road, Stanford, <a href="http://maps.google.co.uk/maps?f=d&source=s_d&saddr=Old+Warden,+Biggleswade,+Central+Bedfordshire+SG18+9DX,+UK&daddr=52.081721,-0.341091+to:SG18+9JD&geocode=FSDDGgMdDAT7_ykft30wyMt3SDESOsaBh3s7ag%3B%3BFalNGgMd_D_7_yn1yJjXcst3SDFfrk-98lOqHw&hl=en&mra=dpe&mrsp=1&sz=13&via=1&sll=52.070116,-0.312767&sspn=0.062468,0.149002&ie=UTF8&z=13">SG18 9JD</a><br/>
       01462 812293 / <a href="mailto:greenmanstanford@yahoo.co.uk">E-mail</a></p>
    </td>
    <td>Bed &amp; Breakfast</td>
    <td>£50 - £85</td>
    <td>4 miles</td>
  </tr>
  <tr>
    <td>
      <p><a href="http://www.strattonhouse-hotel.com">Stratton House Hotel</a><br/>
      London Road, Biggleswade, <a href="http://maps.google.co.uk/maps?f=d&source=s_d&saddr=Old+Warden,+Biggleswade,+Central+Bedfordshire+SG18+9DX,+UK&daddr=52.086468,-0.340405+to:sg188ed&hl=en&geocode=FSDDGgMdDAT7_ykft30wyMt3SDESOsaBh3s7ag%3B%3BFVbGGgMd7RT8_ynloVbAOMx3SDE-JoeUwV7sjQ&mra=dpe&mrsp=1&sz=13&via=1&sll=52.088683,-0.291653&sspn=0.062442,0.149002&ie=UTF8&z=13">SG18 8ED</a><br/>
       01767 312442 / <a href="mailto:info@strattonhouse-hotel.com">E-mail</a></p>
    </td>
    <td>Hotel (2 star)</td>
    <td>£64 - £93</td>
    <td>4.8 miles</td>
  </tr>
  <tr>
    <td>
      <p><a href="http://www.barnshotelbedford.co.uk">The Barns Hotel</a><br/>
      Cardington Road, Bedford, <a href="http://maps.google.co.uk/maps?f=d&source=s_d&saddr=Old+Warden,+Biggleswade,+Central+Bedfordshire+SG18+9DX,+UK&daddr=Bedford+MK44+3SA&hl=en&geocode=FSDDGgMdDAT7_ykft30wyMt3SDESOsaBh3s7ag%3BFRBdGwMdpWv5_ykhb91aYLZ3SDFawFsvc3w1aQ&mra=ls&sll=52.106285,-0.300395&sspn=0.062417,0.149002&ie=UTF8&ll=52.10176,-0.378857&spn=0.062423,0.149002&z=13">MK44 3SA</a><br/>
       01234 270044 / <a href="mailto:sales@barnshotelbedford.co.uk">E-mail</a></p>
    </td>
    <td>Hotel</td>
    <td>£78 - £98</td>
    <td>6.6 miles</td>
  </tr>
  <tr>
    <td>
      <p><a href="http://www.river-lodge.co.uk">The River Lodge</a><br/>
      Mill Lane, Sandy, <a href="http://maps.google.co.uk/maps?f=d&source=s_d&saddr=Old+Warden,+Biggleswade,+Central+Bedfordshire+SG18+9DX,+UK&daddr=52.086679,-0.340919+to:sg191nh&hl=en&geocode=FSDDGgMdDAT7_ykft30wyMt3SDESOsaBh3s7ag%3B%3BFQFjGwMdHHz7_ymbWjTpScl3SDEnVnwJizFdiA&mra=dpe&mrsp=1&sz=13&via=1&sll=52.106285,-0.300395&sspn=0.062417,0.149002&ie=UTF8&z=13">SG19 1NH</a><br/>
       01767 692170 / <a href="mailto:theriverlodge@googlemail.com">E-mail</a></p>
    </td>
    <td>Bed &amp; Breakfast</td>
    <td>£45 - £70</td>
    <td>6.7 miles</td>
  </tr>
  <tr>
    <td>
      <p><a href="http://www.holidayinn.com/hotels/gb/en/sandy/sdyuk/hoteldetail">Holiday Inn</a><br/>
      Girton Bridge, London Road, Sandy, <a href="http://maps.google.co.uk/maps?f=d&source=s_d&saddr=Old+Warden,+Biggleswade,+Central+Bedfordshire+SG18+9DX,+UK&daddr=52.0861558,-0.3400549+to:SG19+1NA&hl=en&geocode=FSDDGgMdDAT7_ykft30wyMt3SDESOsaBh3s7ag%3BFYvFGgMdqs_6_ynX5yOjNcp3SDFBMfW3qBwOEw%3BFTNoGwMdTWv7_ykXwXjlN8l3SDGTcdXaqRwOHQ&mra=dpe&mrsp=1&sz=13&via=1&sll=52.106255,-0.30007&sspn=0.062417,0.149002&ie=UTF8&ll=52.109352,-0.30899&spn=0.062413,0.149002&z=13">SG19 1NA</a><br/>
       01767 692220 / <a href="mailto:sandy@holidayinns.co.uk">E-mail</a></p>
    </td>
    <td>Bed &amp; Breakfast</td>
    <td>£50 - £68</td>
    <td>6.8 miles</td>
  </tr>
  <tr>
    <td>
      <p><a href="http://www.bedfordswanhotel.co.uk">The Swan Hotel</a><br/>
      The Embankment, Bedford, <a href="http://maps.google.co.uk/maps?f=d&source=s_d&saddr=Old+Warden,+Biggleswade,+Central+Bedfordshire+SG18+9DX,+UK&daddr=mk401rw&hl=en&geocode=FSDDGgMdDAT7_ykft30wyMt3SDESOsaBh3s7ag%3BFUuEGwMdYub4_ylPwIaMxLZ3SDHv4O401q-f9Q&mra=ls&sll=52.109352,-0.30899&sspn=0.062413,0.149002&ie=UTF8&ll=52.109668,-0.402374&spn=0.124825,0.298004&z=12">MK40 1RW</a><br/>
       01234 346565 / <a href="mailto:info@bedfordswanhotel.co.uk">E-mail</a></p>
    </td>
    <td>Hotel (4 star)</td>
    <td>£99+</td>
    <td>8.5 miles</td>
  </tr>
  <tr>
    <td>
      <p><a href="http://www.embankmentbedford.co.uk">The Embankment Hotel</a><br/>
      The Embankment, Bedford, <a href="http://maps.google.co.uk/maps?f=d&source=s_d&saddr=Old+Warden,+Biggleswade,+Central+Bedfordshire+SG18+9DX,+UK&daddr=mk403pd&hl=en&geocode=FSDDGgMdDAT7_ykft30wyMt3SDESOsaBh3s7ag%3BFZ-EGwMdoP34_ykVTMeMwrZ3SDFNBy1VXysAOw&mra=ls&sll=52.109668,-0.402374&sspn=0.124825,0.298004&ie=UTF8&ll=52.109246,-0.398941&spn=0.124826,0.298004&z=12">MK40 3PD</a><br/>
       01234 261332 / <a href="mailto:embankment@peachpubs.com">E-mail</a></p>
    </td>
    <td>Hotel (4 star)</td>
    <td>£85 - £115</td>
    <td>9 miles</td>
  </tr>
</table>
